### ISSUE TITLE
How to generate proto for js like the example?

### ISSUE THREAD

**Issue by frrg** [percybolmer/grpcexample#2]
Hello. 

I'am interested to your grpcexample and i want to ask how to generate proto for web based client. 

Thankyou

**Comment by percybolmer** [comment]
protoc service.proto --js\_out=import\_style=commonjs,binary:./../ui/src/ --grpc-web\_out=import\_style=commonjs,mode=grpcwebtext:./../ui/src/ --go-grpc\_out=. --go\_out=.

Thats the command I run. 

You can read the full description on my blog 
https://programmingpercy.tech/blog/using-grpc-tls-go-react-no-reverse-proxy/
